### ISSUE TITLE
bp指令错误识别num+mode参数

### ISSUE THREAD

**Issue by Exsper** [KanonTeam/KanonBot-Pulic#1]
** 问题描述 **
!bp同时给定mode和num参数时无法准确识别参数

** 复现方法 **
Exsper: !bp3:0

猫猫: 没这个人！

** 其他信息 **

**Comment by timi137137** [comment]
OK，收到了

**Comment by Monodesu** [comment]
fixed.

**Comment by Exsper** [comment]
mode和num识别反了，请修复

**Comment by Monodesu** [comment]
fixed

**Comment by Exsper** [comment]
num好像没用了，bp10:1和bp3:1是一样的，都返回bp#1，mode是对的
不是太重要的问题，等有精力再修就好，毕竟我这要求太小众了

**Comment by Monodesu** [comment]
已经好了..忘记删一串代码了

**Comment by Monodesu** [comment]
远古代码 也确实没有什么维护的必要了
